version: '3.8'

services:
  frontend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount Let's Encrypt certificates
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    environment:
      - NODE_ENV=production 